USE SOPHO;

DELETE FROM book;

INSERT INTO `book` VALUES 
  (1, 'https://www.amazon.com/Rational-Optimist-How-Prosperity-Evolves/dp/006145205X', 
    "https://m.media-amazon.com/images/I/51uuXs3tzlL._SY466_.jpg",
    "The Rational Optimist: How Prosperity Evolves",
    "Matt Ridley", "non-fiction"),
  (2, 'https://www.amazon.com/Skin-Game-Hidden-Asymmetries-Daily/dp/0425284646', 
    "https://m.media-amazon.com/images/I/71tG+8MoHgL._SY466_.jpg",
    "Skin in the Game: Hidden Asymmetries in Daily Life (Incerto)",
    "Nassim Nicholas Taleb", "non-fiction"),
  (3, 'https://www.amazon.com/Steve-Jobs-Walter-Isaacson/dp/1451648537', 
    "https://m.media-amazon.com/images/I/61d7gLTQ4bL._SY466_.jpg",
    "Steve Jobs",
    "Walter Isaacson", "non-fiction"),
  (4, 'https://www.amazon.com/The-Three-Body-Problem-audiobook/dp/B00P00QPPY', 
    "https://m.media-amazon.com/images/I/51pHYR3yHaL.jpg",
    "The Three-Body Problem",
    "Cixin Liu", "fiction"),
  (5, 'https://www.amazon.com/gp/product/143914995X', 
    "https://m.media-amazon.com/images/I/71m6TgqkfvL._SY466_.jpg",
    "The Lessons of History",
    "Will Durant and Ariel Durant", "non-fiction"),
  (6, 'https://www.amazon.com/gp/product/1578645018', 
    "https://m.media-amazon.com/images/I/81bvEcXd0yL._SX606_.jpg",
    "Poor Charlie's Almanack: The Wit and Wisdom of Charles T. Munger",
    "Charles T. Munger", "non-fiction"),
  (7, 'https://www.amazon.com/gp/product/0735213933', 
    "https://m.media-amazon.com/images/I/81WT49PEQsL._SY466_.jpg",
    "Reality Is Not What It Seems: The Journey to Quantum Gravity",
    "Carlo Rovelli", "non-fiction"),
  (8, 'https://www.amazon.com/Pre-Suasion-Revolutionary-Way-Influence-Persuade-ebook/dp/B01C36E2YS', 
    "https://m.media-amazon.com/images/I/71gC-ZXcKfL._SY466_.jpg",
    "Pre-Suasion: A Revolutionary Way to Influence and Persuade",
    "Robert B. Cialdini", "non-fiction"),
  (9, 'https://www.amazon.com/Beginning-Infinity-Explanations-Transform-World/dp/0143121359', 
    "https://m.media-amazon.com/images/I/81kgWVO7VkL._SY466_.jpg",
    "The Beginning of Infinity: Explanations That Transform the World",
    "David Deutsch", "non-fiction"),
  (10, 'https://www.amazon.com/G%C3%B6del-Escher-Bach-Eternal-Golden/dp/0465026567', 
    "https://m.media-amazon.com/images/I/51zU0Zk9zLL._SY466_.jpg",
    "Gödel, Escher, Bach: An Eternal Golden Braid",
    "Douglas R Hofstadter", "non-fiction"),
  (11, 'https://www.amazon.com/Selfish-Gene-Anniversary-Landmark-Science/dp/0198788606', 
    "https://m.media-amazon.com/images/I/61CXvkfdXlL._SY466_.jpg",
    "The Selfish Gene: 40th Anniversary Edition",
    "Richard Dawkins", "non-fiction"),
  (12, 'https://www.amazon.com/Extreme-Ownership-Paperback-ISBN-978-1250270962/dp/B096RJM5L7', 
    "https://m.media-amazon.com/images/I/51ZPQERZSVL._SY466_.jpg",
    "Extreme Ownership: How U.S. Navy SEALs Lead and Win",
    "Jocko Willink and Leif Babin", "non-fiction"),
  (13, 'https://www.amazon.com/Guns-Germs-Steel-Fates-Societies/dp/0393354326', 
    "https://m.media-amazon.com/images/I/71BByzm98gL._SY466_.jpg",
    "Guns, Germs, and Steel: The Fates of Human Societies",
    "Jared Diamond Ph.D.", "non-fiction"),
  (14, 'https://www.amazon.com/Moral-Animal-Science-Evolutionary-Psychology-ebook/dp/B00486U8N6', 
    "https://m.media-amazon.com/images/I/51449gYdjhL._SY466_.jpg",
    "The Moral Animal: Why We Are, the Way We Are: The New Science of Evolutionary Psychology",
    "Robert Wright", "non-fiction"),
  (15, 'https://www.amazon.com/Omnivores-Dilemma-Natural-History-Meals/dp/0143038583', 
    "https://m.media-amazon.com/images/I/81xBWiuTmGL._SY466_.jpg",
    "The Omnivore's Dilemma: A Natural History of Four Meals",
    "Michael Pollan", "non-fiction"),
  (16, 'https://www.amazon.com/Atomic-Habits-Proven-Build-Break/dp/0735211299', 
    "https://m.media-amazon.com/images/I/812eE1lO0dL._SY466_.jpg",
    "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
    "James Clear", "non-fiction"),
  (17, 'https://www.amazon.com/Raising-Good-Humans-Parenting-Confident/dp/1684033888', 
    "https://m.media-amazon.com/images/I/71TWKixwzWL._SY466_.jpg",
    "Raising Good Humans: A Mindful Guide to Breaking the Cycle of Reactive Parenting and Raising Kind, Confident Kids",
    "Hunter Clarke-Fields MSAE", "non-fiction"),
  (18, 'https://www.amazon.com/dp/1250066115', 
    "https://m.media-amazon.com/images/I/81RvGjUWqlL._SY466_.jpg",
    "How Not to Die: Discover the Foods Scientifically Proven to Prevent and Reverse Disease",
    "Michael Greger MD and Gene Stone", "non-fiction"),
  (19, 'https://www.amazon.com/Homo-Deus-Brief-History-Tomorrow/dp/0062464345', 
    "https://m.media-amazon.com/images/I/81hMjlT14ML._SY466_.jpg",
    "Homo Deus: A Brief History of Tomorrow",
    "Yuval Noah Harari", "non-fiction"),
  (20, 'https://www.amazon.com/Lifespan-audiobook/dp/B07QGH1Q43', 
    "https://m.media-amazon.com/images/I/41OHsYaqo3L._SY445_SX342_.jpg",
    "Lifespan: Why We Age – and Why We Don’t Have To",
    "Dr David A. Sinclair", "non-fiction");


Cancel https://www.scribd.com/

DELETE from 

DELETE FROM prompt;

INSERT INTO `prompt` VALUES 
  (20, NULL, 2, 1, 1, 'unknown_category', 
  "You are the detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.", 
  "Produce 5-10 paragraphs that cover the main points of the book %s by %s (without any introductory paragraphs -- jump right in to a summary of the beginning of the book).  If the book has multiple chapters that reflect how the content naturally organizes, please create a summary for each chapter with a paragraph of text that explains the key points of that chapter.  If the book is not naturally organized into chapters then summarize into paragraphs, each one explaining a portion of the book's content. Do not give introductory or concluding paragraphs -- just provide paragraphs separated by newlines where each paragraph represents a distinct part of the summary.",
  "summary", "Summary"),
  (21, 20, 2, 2, 1, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.", 
  "The book %s by %s talks has a section about %s.\n\nPlease explain what the author meant in that section by summarizing into 5-10 paragraphs, each one explaining a portion of the section and separated by newlines.",
  "summary", "Summary"),
  (22, 21, 2, 3, 1, 'unknown_category', 
  "Response with the following settings:\n mode: long-form, detail_level: high, tone: imitate-author, task: Provide a detailed response in the tone and language style of the author", 
  "Here is a summary of a section of the book %s by %s: %s\n\nInstructions:\n Using the summary provided above, elaborate on the points mentioned, staying strictly within the context and content of this section. Aim to match the language and style of the original author as closely as possible.  Do not give introductory or concluding paragraphs, or mention the author's name.  Your response should be 5-10 paragraphs separated by newlines, where each paragraph is devoted to a distinct aspect of the larger points the author makes that are referred to by the summary.",
  "summary", "Summary"),
  (23, 21, 2, 3, 2, 'unknown_category', 
  "Response with the following settings:\n mode: long-form, detail_level: high, tone: imitate-author, task: Provide a detailed response in the tone and language style of the author", 
  "I have a summary of a section from the book %s by %s. Drawing from the summary provided and in the tone and language of the original text, please provide several compelling and memorable examples that highlight and elucidate the main points of this section.  Do not give introductory or concluding paragraphs, or mention the author's name.  Each paragraph should be separated by newlines be a distinct example.  Here's the summary:\n\n%s",
  "examples", "Examples"),
  (24, 21, 2, 3, 3, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.", 
  "I have a summary of a section from the book %s by %s. I'd like to understand the larger significance and context of this section within the broader scope of science, history, or its relevant field. Additionally, please provide major alternate viewpoints or interpretations from other notable thinkers or critics on this section. Do not give introductory or concluding paragraphs -- just provide paragraphs separated by newlines where each paragraph represents a distinct piece of analysis. Here's the summary:\n\n%s",
  "discussion", "Discussion"),
  (25, 21, 2, 3, 4, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.", 
  "I have a summary of a section from the book %s by %s. Drawing from the content that the summary refers to, please produce 10-20 multiple choice questions to test knowledge of this contet.  Respond with a valid JSON array that lists these questions as [{\"question\" : \"text of the question\",\"A)\":\"text of question A\",\"B)\":\"text of question B\",\"C)\":\"text of question C\",\"D)\":\"text of question D\",\"answer\":\"correct asnwer (A-D)\"},\"explanation\":\"a few sentences to explain why the correct answer is correct\"].  The explanation should match the tone and language of the original text.  Here's the summary:\n\n%s",
  "test", "Test Me"),

  (1, NULL, 1, 1, 1, 'unknown_category', 
  "You are the detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "Summarize the book %s by %s.  If the book has multiple chapters that reflect how the content naturally organizes, please create a summary for each chapter with a paragraph of text that explains the key points of that chapter.  If the book is not naturally organized into chapters then summarize into 5-10 paragraphs, each one explaining a portion of the book's content. Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "summary", "Summary"),
  (2, NULL, 1, 1, 2, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "What are some specific examples discussed in the book %s by %s?  Try to come up with about 10 examples that illustrate the thesis of the book and write a detailed paragraph for each example. Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "examples", "Examples"),
  (3, NULL, 1, 1, 3, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand a particular book as well as work by other writers that explore related concepts.  Your answers will explain to the best of your abilities and be truthful.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "What do other writers have to say about the content of the book %s by %s?  In particular, please write 5-10 paragraphs that give detailed explanations of these thoughts.  These paragraphs should span the range of common arguments from others, both in support and in opposition to the book (and various different oppositional arguments, and provide sources).  Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "discussion", "Discussion"),
  (4, NULL, 1, 1, 4, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books and wants to be tested on their knowledge.  Your will ask questions that are relevant to the conten of the book, show detailed knowledge and be truthful.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "Can you provide 10-20 multiple choice questions to test knowledge of the book %s by %s?  Respond with a valid JSON array that lists these questions as [{'question' : 'text of the question','A)':'text of question A','B)':'text of question B','C)':'text of question C','D)':'text of question D','answer':'correct asnwer (A-D)'},'explanation':'a few sentences to explain why the correct answer is correct']",
  "test", "Test Me"),
  (5, 1, 1, 2, 1, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "The book %s by %s talks has a section about %s.\n\nPlease explain what the author meant in that section by summarizing into 5-10 paragraphs, each one explaining a portion of the section. Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "summary", "Summary"),
  (6, 1, 1, 2, 2, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "What are some specific examples discussed in the book %s by %s specifically to the section about %s?n\nTry to come up with about 10 examples that illustrate the arguments of this section and write a detailed paragraph for each example. Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "examples", "Examples"),
  (7, 1, 1, 2, 3, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "What do other writers have to say about the content of the book %s by %s, specifically to the section about %s?n\nIn particular, please write 5-10 paragraphs that give detailed explanations of these thoughts.  These paragraphs should span the range of common arguments from others, both in support and in opposition to the section (and various different oppositional arguments, and provide sources).  Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "discussion", "Discussion"),
  (8, 1, 1, 2, 4, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "Can you provide 10-20 multiple choice questions to test knowledge of the book %s by %s, specifically to the section about %s?n\nRespond with a valid JSON array that lists these questions as [{'question' : 'text of the question','A)':'text of question A','B)':'text of question B','C)':'text of question C','D)':'text of question D','answer':'correct asnwer (A-D)'},'explanation':'a few sentences to explain why the correct answer is correct']",
  "test", "Test Me"),
  (9, 2, 1, 2, 1, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "The following is an example from the book %s by %s: %s.\n\nPlease explain what the author means by this example by summarizing into 5-10 paragraphs, each one explaining a portion of the example. Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "summary", "Summary"),
  (10, 2, 1, 2, 2, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "The following is an example from the book %s by %s: %s.\n\nTry to come up with about 10 further examples that illustrate the author's example and write a detailed paragraph for each example. Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "examples", "Examples"),
  (11, 2, 1, 2, 3, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "The following is an example from the book %s by %s: %s. What do other writers have to say about the meaning and validity of that example?  In particular, please write 5-10 paragraphs that give detailed explanations of these thoughts.  These paragraphs should span the range of common arguments from others, both in support and in opposition to the example (and various different oppositional arguments, and provide sources).  Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "discussion", "Discussion"),
  (12, 2, 1, 2, 4, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "Can you provide 10-20 multiple choice questions to test knowledge of the book %s by %s, specifically related to the example %s?n\nRespond with a valid JSON array that lists these questions as [{'question' : 'text of the question','A)':'text of question A','B)':'text of question B','C)':'text of question C','D)':'text of question D','answer':'correct asnwer (A-D)'},'explanation':'a few sentences to explain why the correct answer is correct']",
  "test", "Test Me"),
  (13, 3, 1, 2, 1, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "The following is a discussion about the book %s by %s: %s.\n\nPlease explain this discussion by summarizing into 5-10 paragraphs, each one explaining a portion of the discussion. Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "summary", "Summary"),
  (14, 3, 1, 2, 2, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "The following is a discussion about the book %s by %s: %s.\n\nTry to come up with about 10 further examples that illustrate the arguments of the discussion and write a detailed paragraph for each example. Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "examples", "Examples"),
  (15, 3, 1, 2, 3, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "Can you provide 10-20 multiple choice questions to test knowledge of discussion about the book %s by %s: %s?n\nRespond with a valid JSON array that lists these questions as [{'question' : 'text of the question','A)':'text of question A','B)':'text of question B','C)':'text of question C','D)':'text of question D','answer':'correct asnwer (A-D)'},'explanation':'a few sentences to explain why the correct answer is correct']",
  "test", "Test Me"),
  (16, 4, 1, 2, 1, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "In the book %s by %s, one question is %s and the answer is %s.\n\nPlease explain the context from the book around this question and answer by summarizing into 5-10 paragraphs, each one explaining a portion of this context. Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "summary", "Summary"),
  (17, 4, 1, 2, 2, 'unknown_category', 
  "You are a detail-oriented professor with complete and accurate information about books.  You are talking to a college student eager to understand books.  Your answers will explain to the best of your abilities and be truthful.  You will go deep into details.  You will always respond in json format.  If you don't know the answer to a question, respond with {'error' : 'I do not know'}", 
  "In the book %s by %s, one question is %s and the answer is %s. What do other writers have to say about this question and answer, both in the context of the book as well as the wider world?  In particular, please write 5-10 paragraphs that give detailed explanations of these thoughts.  These paragraphs should span the range of common arguments from others, both in support and in opposition to the answer (and various different oppositional arguments, and provide sources).  Respond with a valid JSON array that lists these paragraphs as ['paragraph 1'], ['paragraph 2'], ['paragraph 3']",
  "discussion", "Discussion");


bad response_piece_ids

17225877684833147508
8345947978927493534
1843729306225647123
14651579357573500744
8587871527997959085